export enum ContentType {
    JSON = "application/json",
    XML = "application/xml",
    TEXT_HTML = "text/html",
    TEXT_PLAIN = "text/plain",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    MULTIPART_FORM_DATA = "multipart/form-data",
    OCTET_STREAM = "application/octet-stream",
    GIF = "image/gif",
    JPEG = "image/jpeg",
    PNG = "image/png",
    SVG = "image/svg+xml",
    PDF = "application/pdf",
    ZIP = "application/zip",
    CSV = "text/csv",
    ICO = "image/x-icon",
    MP4 = "video/mp4",
    MP3 = "audio/mpeg",
    WEBM = "video/webm",
    WAV = "audio/wav",
}